### ISSUE TITLE
Problems with UIKIT

### ISSUE THREAD

**Issue by pcout** [lokesh-coder/pretty-checkbox#13]
I'm having problems with this when using UIKIT icon library (https://getuikit.com/docs/icon).

- The icon inside the checkbox doesn't disappears when I click on it.
- The colors (success, etc) overlap the icons.
- The outline colors only affect the box borders, not with the icons colors. They don´t change color at all.

Can you help me ?
Thanks. Great job.

**Comment by lokesh-coder** [comment]
Hello @pcout ,
Thanks for pointing out the issues clearly.
I haven't tested with UIKit font icons yet. But now, I will check that and post you an update.

**Comment by pcout** [comment]
OK. Thanks.

**Comment by pcout** [comment]
Hi @lokesh-coder ,
Any news on this ?

**Comment by lokesh-coder** [comment]
Hi @pcout ,

I have updated the library to version 3 which has the support to [add UIKit icons](https://lokesh-coder.github.io/pretty-checkbox/#svg-lib).

Please have a look at new [changes](https://github.com/lokesh-coder/pretty-checkbox/blob/master/README.md)

The problem was, UIKit is not a font icons, but a SVG. UIKit dynamically injects svg markup. 

Feel free to open it again if you got any questions.
Thanks!
